//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class ALOHA_Articles : BaseModel
    {
        public ALOHA_Articles()
        {
            this.OITM_ALOHA = new HashSet<OITM_ALOHA>();
        }
    
        public int IdALOHA_Articles { get; set; }
        public string Categories { get; set; }
        public string code { get; set; }
        public string State { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public int DetailInvoiceALOHAIdDetailInvoiceALOHA { get; set; }
    
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ICollection<OITM_ALOHA> OITM_ALOHA { get; set; }
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual DetailInvoiceALOHA DetailInvoiceALOHA { get; set; }
    }
}
