//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class ATC1_Attachments : BaseModel
    {
        public int IdAtached { get; set; }
        public int AbsEntry { get; set; }
        public int Line { get; set; }
        public string srcPath { get; set; }
        public string trgtPath { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
        public System.DateTime Date { get; set; }
        public int UsrID { get; set; }
        public string Copied { get; set; }
        public string Override { get; set; }
        public int IdEspecialOrder { get; set; }
    
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ORDR_SpecialOrder ORDR_SpecialOrder { get; set; }
    }
}
