//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class CashMissing : BaseModel
    {
        public int IdCashMissing { get; set; }
        public decimal Amount { get; set; }
        public string CardCode { get; set; }
        public System.DateTime Date { get; set; }
        public string Comments { get; set; }
        public string UserAuthorization { get; set; }
        public string StateL { get; set; }
        public System.DateTime CreatedDateL { get; set; }
        public string CreatedByL { get; set; }
        public string ModifiedByL { get; set; }
        public System.DateTime ModifiedDateL { get; set; }
    }
}
