//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class Checkbook : BaseModel
    {
        public Checkbook()
        {
            this.SeriesCheckbook = new HashSet<SeriesCheckbook>();
        }
    
        public int IdCheckbookL { get; set; }
        public System.DateTime DateL { get; set; }
        public string SerieL { get; set; }
        public int InitialNumL { get; set; }
        public int NextNumberL { get; set; }
        public int LastNumL { get; set; }
        public string StateL { get; set; }
        public System.DateTime CreatedDateL { get; set; }
        public string ModifiedByL { get; set; }
        public string CreatedByL { get; set; }
        public System.DateTime ModifiedDateL { get; set; }
    
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ICollection<SeriesCheckbook> SeriesCheckbook { get; set; }
    }
}
