//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class Colors : BaseModel
    {
        public Colors()
        {
            this.Cover = new HashSet<Cover>();
            this.Ribbon = new HashSet<Ribbon>();
            this.Filling = new HashSet<Filling>();
        }
    
        public int IdColors { get; set; }
        public string Name { get; set; }
        public int CoverIdCover { get; set; }
    
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ICollection<Cover> Cover { get; set; }
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ICollection<Ribbon> Ribbon { get; set; }
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ICollection<Filling> Filling { get; set; }
    }
}
