//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class DetailInvoiceALOHA : BaseModel
    {
        public DetailInvoiceALOHA()
        {
            this.ALOHA_Articles = new HashSet<ALOHA_Articles>();
        }
    
        public int IdDetailInvoiceALOHA { get; set; }
        public int InvoiceALOHAIdInvoiceALOHA { get; set; }
        public int Category { get; set; }
        public System.DateTime DOB { get; set; }
        public string EntryId { get; set; }
        public string Property1 { get; set; }
        public System.DateTime Hour { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Sysdate { get; set; }
        public int TermId { get; set; }
        public int Type { get; set; }
    
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ICollection<ALOHA_Articles> ALOHA_Articles { get; set; }
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual InvoiceALOHA InvoiceALOHA { get; set; }
    }
}
