//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class Documents : BaseModel
    {
        public Documents()
        {
            this.UserDocument = new HashSet<UserDocument>();
            this.UserAuthorization = new HashSet<UserAuthorization>();
        }
    
        public string ObjType { get; set; }
        public string DocumentName { get; set; }
    
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ICollection<UserDocument> UserDocument { get; set; }
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ICollection<UserAuthorization> UserAuthorization { get; set; }
    }
}
