//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class IGN1_GoodsReceiptDetail : BaseModel
    {
        public int IdGoodReceiptDetail { get; set; }
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public string LineStatus { get; set; }
        public string ItemCode { get; set; }
        public string Dscription { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public string WhsCode { get; set; }
        public string AcctCode { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string UseBaseUn { get; set; }
        public string ObjType { get; set; }
        public string UnitMsr { get; set; }
        public string CodeBars { get; set; }
        public System.DateTime CreatedDateL { get; set; }
        public string ModifiedByL { get; set; }
        public string CreatedByL { get; set; }
        public System.DateTime ModifiedDateL { get; set; }
        public int IdGoodReceiptL { get; set; }
    
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual OIGN_GoodsReceipt OIGN_GoodsReceipt { get; set; }
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual OITM_Articles OITM_Articles { get; set; }
    }
}
