//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class INV1_SalesDetail : BaseModel
    {
        public int IdSaleDetail { get; set; }
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public string ItemCode { get; set; }
        public string Dscription { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public string WhsCode { get; set; }
        public string AcctCode { get; set; }
        public string OcrCode { get; set; }
        public int IdSaleL { get; set; }
        public int IdPaymentType { get; set; }
        public int IdRoyalty { get; set; }
        public string TaxStatus { get; set; }
    
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual OINV_Sales OINV_Sales { get; set; }
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual PaymentTypes PaymentTypes { get; set; }
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual PaymentTypes PaymentTypes1 { get; set; }
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual OITM_Articles OITM_Articles { get; set; }
    }
}
