//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class InvoiceALOHA : BaseModel
    {
        public InvoiceALOHA()
        {
            this.DetailInvoiceALOHA = new HashSet<DetailInvoiceALOHA>();
        }
    
        public int IdInvoiceALOHA { get; set; }
        public System.DateTime Date { get; set; }
        public string State { get; set; }
        public double Credit { get; set; }
        public double Cash { get; set; }
        public string correlative { get; set; }
    
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ICollection<DetailInvoiceALOHA> DetailInvoiceALOHA { get; set; }
    }
}
