//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class LocalUsers : BaseModel
    {
        public LocalUsers()
        {
            this.UserDocument = new HashSet<UserDocument>();
            this.UserAuthorization = new HashSet<UserAuthorization>();
        }
    
        public System.Guid UserId { get; set; }
        public string NickName { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Position { get; set; }
        public string Locked { get; set; }
        public string CreatedByL { get; set; }
        public System.DateTime CreatedDateL { get; set; }
        public string ModifiedByL { get; set; }
        public System.DateTime ModifiedDateL { get; set; }
        public bool AllowChangePrices { get; set; }
        public bool AllowProcessing { get; set; }
    
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ICollection<UserDocument> UserDocument { get; set; }
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ICollection<UserAuthorization> UserAuthorization { get; set; }
    }
}
