//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<NNM1_Series> NNM1_Series { get; set; }
        public DbSet<OITM_Articles> OITM_Articles { get; set; }
        public DbSet<OITW_BranchArticles> OITW_BranchArticles { get; set; }
        public DbSet<OWHS_Branch> OWHS_Branch { get; set; }
        public DbSet<WTQ1_TransferRequestDetails> WTQ1_TransferRequestDetails { get; set; }
        public DbSet<LocalUsers> LocalUsers { get; set; }
        public DbSet<Documents> Documents { get; set; }
        public DbSet<OWTR_Transfers> OWTR_Transfers { get; set; }
        public DbSet<WTR1_TransferDetails> WTR1_TransferDetails { get; set; }
        public DbSet<UserDocument> UserDocument { get; set; }
        public DbSet<Parameters> Parameters { get; set; }
        public DbSet<OPCH_Purchase> OPCH_Purchase { get; set; }
        public DbSet<ORPC_SupplierCreditNotes> ORPC_SupplierCreditNotes { get; set; }
        public DbSet<PCH1_PurchaseDetail> PCH1_PurchaseDetail { get; set; }
        public DbSet<RPC1_SupplierCreditNoteDetail> RPC1_SupplierCreditNoteDetail { get; set; }
        public DbSet<OIGN_GoodsReceipt> OIGN_GoodsReceipt { get; set; }
        public DbSet<IGN1_GoodsReceiptDetail> IGN1_GoodsReceiptDetail { get; set; }
        public DbSet<IGE1_GoodsIssueDetail> IGE1_GoodsIssueDetail { get; set; }
        public DbSet<OIGE_GoodsIssues> OIGE_GoodsIssues { get; set; }
        public DbSet<Checkbook> Checkbook { get; set; }
        public DbSet<SeriesCheckbook> SeriesCheckbook { get; set; }
        public DbSet<OINV_Sales> OINV_Sales { get; set; }
        public DbSet<INV1_SalesDetail> INV1_SalesDetail { get; set; }
        public DbSet<PaymentTypes> PaymentTypes { get; set; }
        public DbSet<TransactionLog> TransactionLog { get; set; }
        public DbSet<ORDR_SpecialOrder> ORDR_SpecialOrder { get; set; }
        public DbSet<ATC1_Attachments> ATC1_Attachments { get; set; }
        public DbSet<RDR1_SpecialOrderDetail> RDR1_SpecialOrderDetail { get; set; }
        public DbSet<RIN1_ClientCreditNoteDetail> RIN1_ClientCreditNoteDetail { get; set; }
        public DbSet<ORIN_ClientCreditNotes> ORIN_ClientCreditNotes { get; set; }
        public DbSet<ODPI_DownPayment> ODPI_DownPayment { get; set; }
        public DbSet<DPI1_DownPaymentDetail> DPI1_DownPaymentDetail { get; set; }
        public DbSet<Deposits> Deposits { get; set; }
        public DbSet<CashMissing> CashMissing { get; set; }
        public DbSet<OINM_Transaction> OINM_Transaction { get; set; }
        public DbSet<UserAuthorization> UserAuthorizationSet { get; set; }
        public DbSet<ALOHA_Articles> ALOHA_Articles { get; set; }
        public DbSet<OITM_ALOHA> OITM_ALOHA { get; set; }
        public DbSet<AuthorizationLog> AuthorizationLog { get; set; }
        public DbSet<OITB_Groups> OITB_Groups { get; set; }
        public DbSet<InvoiceALOHA> InvoiceALOHA { get; set; }
        public DbSet<DetailInvoiceALOHA> DetailInvoiceALOHA { get; set; }
        public DbSet<Colors> Colors { get; set; }
        public DbSet<Cover> Cover { get; set; }
        public DbSet<Ribbon> Ribbon { get; set; }
        public DbSet<Filling> Filling { get; set; }
        public DbSet<OCRD_BusinessPartner> OCRD_BusinessPartner { get; set; }
        public DbSet<OWTQ_TransferRequest> OWTQ_TransferRequest { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UCakes> UCakes { get; set; }
        public DbSet<UCategory> UCategory { get; set; }
        public DbSet<UColor_Covert> UColor_Covert { get; set; }
        public DbSet<UColor_Flower> UColor_Flower { get; set; }
        public DbSet<UColor_Ribbon> UColor_Ribbon { get; set; }
        public DbSet<UColor_top> UColor_top { get; set; }
        public DbSet<UCover> UCover { get; set; }
        public DbSet<UEspecialty> UEspecialty { get; set; }
        public DbSet<UFlower> UFlower { get; set; }
        public DbSet<UMovements> UMovements { get; set; }
        public DbSet<UMovements_Acc> UMovements_Acc { get; set; }
        public DbSet<UStyle> UStyle { get; set; }
        public DbSet<UStyle_filler> UStyle_filler { get; set; }
    }
}
