//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class ODPI_DownPayment : BaseModel
    {
        public ODPI_DownPayment()
        {
            this.INV1_SalesDetail = new HashSet<DPI1_DownPaymentDetail>();
        }
    
        public int IdDownPayment { get; set; }
        public int DocEntry { get; set; }
        public int DocNum { get; set; }
        public string CANCELED { get; set; }
        public string DocStatus { get; set; }
        public string ObjType { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public string CardCode { get; set; }
        public string NumAtCard { get; set; }
        public decimal DocTotal { get; set; }
        public string Comments { get; set; }
        public string JrnlMemo { get; set; }
        public Nullable<short> Series { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public System.DateTime CreatedDateL { get; set; }
        public string CreatedByL { get; set; }
        public string ModifiedByL { get; set; }
        public System.DateTime ModifiedDateL { get; set; }
        public string StateL { get; set; }
        public string ObjType1 { get; set; }
        public string DocType { get; set; }
        public string WhsCode { get; set; }
        public bool HasToBeSync { get; set; }
    
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ICollection<DPI1_DownPaymentDetail> INV1_SalesDetail { get; set; }
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual OWHS_Branch OWHS_Branch { get; set; }
    }
}
