//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class OINM_Transaction : BaseModel
    {
        public int IdTransaction { get; set; }
        public int TransNum { get; set; }
        public int TransType { get; set; }
        public System.DateTime DocDate { get; set; }
        public System.DateTime DocDueDate { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string Comments { get; set; }
        public string JrnMemo { get; set; }
        public int DocTime { get; set; }
        public string ItemCode { get; set; }
        public string Dscription { get; set; }
        public Nullable<decimal> InQty { get; set; }
        public Nullable<decimal> OutQty1 { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string SerialNum { get; set; }
        public string WareHouse { get; set; }
        public bool HasToBeSync { get; set; }
    }
}
