//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class OITW_BranchArticles : BaseModel
    {
        public string ItemCode { get; set; }
        public string WhsCode { get; set; }
        public Nullable<decimal> OnHand { get; set; }
        public Nullable<decimal> OnHand1 { get; set; }
        public Nullable<decimal> IsCommited { get; set; }
        public Nullable<decimal> OnOrder { get; set; }
        public Nullable<decimal> MinStock { get; set; }
        public Nullable<decimal> MaxStock { get; set; }
        public Nullable<decimal> MinOrder { get; set; }
        public string Locked { get; set; }
        public System.DateTime LastSyncDateL { get; set; }
    
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual OITM_Articles OITM_Articles { get; set; }
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual OWHS_Branch OWHS_Branch { get; set; }
    }
}
