//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class OWTQ_TransferRequest : BaseModel
    {
        public OWTQ_TransferRequest()
        {
            this.WTQ1_TransferRequestDetails = new HashSet<WTQ1_TransferRequestDetails>();
        }
    
        public Nullable<int> DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public string CANCELED { get; set; }
        public string DocStatus { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public string CardCode { get; set; }
        public string Comments { get; set; }
        public string JrnlMemo { get; set; }
        public Nullable<short> Series { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public string Filler { get; set; }
        public int IdTransferRequestL { get; set; }
        public int StateL { get; set; }
        public System.DateTime DeliveryDateL { get; set; }
        public System.DateTime CreatedDateL { get; set; }
        public string ModifiedByL { get; set; }
        public Nullable<System.DateTime> LastSyncDateL { get; set; }
        public string ObjType { get; set; }
        public Nullable<System.DateTime> ModifiedDateL { get; set; }
        public string CreatedByL { get; set; }
        public string WhsCode { get; set; }
        public bool HasToBeSync { get; set; }
    
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual OWHS_Branch OWHS_Branch { get; set; }
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ICollection<WTQ1_TransferRequestDetails> WTQ1_TransferRequestDetails { get; set; }
    }
}
