//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class PaymentTypes : BaseModel
    {
        public PaymentTypes()
        {
            this.PaymentTypes1 = new HashSet<PaymentTypes>();
            this.INV1_SalesDetail = new HashSet<INV1_SalesDetail>();
            this.INV1_SalesDetail1 = new HashSet<INV1_SalesDetail>();
        }
    
        public int IdPaymentType { get; set; }
        public string PaymentName { get; set; }
        public string AcctCode { get; set; }
        public bool IsRoyalty { get; set; }
        public int PaymentTypesIdPaymentType { get; set; }
    
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ICollection<PaymentTypes> PaymentTypes1 { get; set; }
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual PaymentTypes PaymentTypes2 { get; set; }
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ICollection<INV1_SalesDetail> INV1_SalesDetail { get; set; }
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual ICollection<INV1_SalesDetail> INV1_SalesDetail1 { get; set; }
    }
}
