//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class TransactionLog : BaseModel
    {
        public int IdTransactionLog { get; set; }
        public string Description { get; set; }
        public short VerificationCode { get; set; }
        public string Code { get; set; }
        public System.DateTime Date { get; set; }
        public string State { get; set; }
        public string CreatedBy { get; set; }
    }
}
