//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigiApi.Model
{
    using System;
    using System.Collections.Generic;using Newtonsoft.Json;
    
    public partial class UStyle_filler : BaseModel
    {
        public string Code { get; set; }
        public int LineId { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public string U_NOMBRE { get; set; }
        public string U_ESTADO { get; set; }
    }
}
